/*
 * Inline every masked icon + the icomoon webfont as data: URIs.
 *
 * Chrome treats each file:// document as an opaque origin, so CSS
 * mask-image fetches and @font-face loads are blocked when the prototype is
 * opened directly instead of served. Data URIs sidestep that, so the page
 * renders identically from file://, a static server, or anywhere else.
 *
 * Run from the repo root:  node _build/inline-icons.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const HTML = path.join(ROOT, 'index.html');
const OUT = path.join(ROOT, 'assets', 'dashboard-icons.css');

const varName = p =>
  '--i-' + p.replace(/^media\/dashboard\//, '').replace(/\.svg$/, '').replace(/[\/_.]/g, '-');

// `file` is relative to assets/, matching how the page and dashboard.css
// write mask URLs (they resolve against the stylesheet, not the document).
const dataUri = file =>
  'data:image/svg+xml;base64,' +
  fs.readFileSync(path.join(ROOT, 'assets', file)).toString('base64');

let html = fs.readFileSync(HTML, 'utf8');

// ---- masked icons referenced from inline --ico custom properties ----------
const used = new Map();
html = html.replace(/--ico:\s*url\((media\/[^)]+\.svg)\)/g, (_, rel) => {
  const name = varName(rel);
  used.set(name, rel);
  return `--ico: var(${name})`;
});

// ---- <img> SVGs: same blocking does not apply, but inline the small ones
// so the shell never depends on a second request ---------------------------
html = html.replace(/src="assets\/(media\/dashboard\/[^"]+\.svg)"/g, (m, rel) => {
  const bytes = fs.statSync(path.join(ROOT, 'assets', rel)).size;
  if (bytes > 6000) return m; // leave the chunky ones on disk
  return `src="${dataUri(rel)}"`;
});

// ---- icomoon, inlined so glyphs survive file:// ---------------------------
const woff = fs.readFileSync(path.join(ROOT, 'assets/fonts/icomoon.woff')).toString('base64');

const lines = [
  '/*',
  ' * Generated by _build/inline-icons.js — do not edit.',
  ' *',
  ' * Icon masks and the icomoon face as data: URIs, so the prototype renders',
  ' * the same whether it is served or opened straight off disk. Chrome blocks',
  ' * both mask-image fetches and webfont loads from file:// origins.',
  ' */',
  '',
  "@font-face {",
  "  font-family: 'icomoon';",
  `  src: url(data:font/woff;base64,${woff}) format('woff');`,
  '  font-weight: normal;',
  '  font-style: normal;',
  '  font-display: block;',
  '}',
  '',
  ':root {',
];
for (const [name, rel] of [...used].sort()) lines.push(`  ${name}: url("${dataUri(rel)}");`);
lines.push('}', '');

fs.writeFileSync(OUT, lines.join('\n'));
fs.writeFileSync(HTML, html);

console.log('icon vars inlined :', used.size);
console.log('stylesheet        :', (fs.statSync(OUT).size / 1024).toFixed(0) + ' KB');
